package com.aps.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class BotSessionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBotSessionAllPropertiesEquals(BotSession expected, BotSession actual) {
        assertBotSessionAutoGeneratedPropertiesEquals(expected, actual);
        assertBotSessionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBotSessionAllUpdatablePropertiesEquals(BotSession expected, BotSession actual) {
        assertBotSessionUpdatableFieldsEquals(expected, actual);
        assertBotSessionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBotSessionAutoGeneratedPropertiesEquals(BotSession expected, BotSession actual) {
        assertThat(expected)
            .as("Verify BotSession auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBotSessionUpdatableFieldsEquals(BotSession expected, BotSession actual) {
        assertThat(expected)
            .as("Verify BotSession relevant properties")
            .satisfies(e -> assertThat(e.getWaPhoneNumber()).as("check waPhoneNumber").isEqualTo(actual.getWaPhoneNumber()))
            .satisfies(e -> assertThat(e.getCurrentState()).as("check currentState").isEqualTo(actual.getCurrentState()))
            .satisfies(e -> assertThat(e.getSessionData()).as("check sessionData").isEqualTo(actual.getSessionData()))
            .satisfies(e -> assertThat(e.getLastActiveAt()).as("check lastActiveAt").isEqualTo(actual.getLastActiveAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBotSessionUpdatableRelationshipsEquals(BotSession expected, BotSession actual) {
        // empty method
    }
}
