package com.aps.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ButtonActionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertButtonActionAllPropertiesEquals(ButtonAction expected, ButtonAction actual) {
        assertButtonActionAutoGeneratedPropertiesEquals(expected, actual);
        assertButtonActionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertButtonActionAllUpdatablePropertiesEquals(ButtonAction expected, ButtonAction actual) {
        assertButtonActionUpdatableFieldsEquals(expected, actual);
        assertButtonActionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertButtonActionAutoGeneratedPropertiesEquals(ButtonAction expected, ButtonAction actual) {
        assertThat(expected)
            .as("Verify ButtonAction auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertButtonActionUpdatableFieldsEquals(ButtonAction expected, ButtonAction actual) {
        assertThat(expected)
            .as("Verify ButtonAction relevant properties")
            .satisfies(e -> assertThat(e.getWaMessageId()).as("check waMessageId").isEqualTo(actual.getWaMessageId()))
            .satisfies(e -> assertThat(e.getButtonId()).as("check buttonId").isEqualTo(actual.getButtonId()))
            .satisfies(e -> assertThat(e.getClickedAt()).as("check clickedAt").isEqualTo(actual.getClickedAt()))
            .satisfies(e -> assertThat(e.getClickedBy()).as("check clickedBy").isEqualTo(actual.getClickedBy()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertButtonActionUpdatableRelationshipsEquals(ButtonAction expected, ButtonAction actual) {
        // empty method
    }
}
