package com.aps.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DeliveryPersonAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDeliveryPersonAllPropertiesEquals(DeliveryPerson expected, DeliveryPerson actual) {
        assertDeliveryPersonAutoGeneratedPropertiesEquals(expected, actual);
        assertDeliveryPersonAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDeliveryPersonAllUpdatablePropertiesEquals(DeliveryPerson expected, DeliveryPerson actual) {
        assertDeliveryPersonUpdatableFieldsEquals(expected, actual);
        assertDeliveryPersonUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDeliveryPersonAutoGeneratedPropertiesEquals(DeliveryPerson expected, DeliveryPerson actual) {
        assertThat(expected)
            .as("Verify DeliveryPerson auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDeliveryPersonUpdatableFieldsEquals(DeliveryPerson expected, DeliveryPerson actual) {
        assertThat(expected)
            .as("Verify DeliveryPerson relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getWaPhoneNumber()).as("check waPhoneNumber").isEqualTo(actual.getWaPhoneNumber()))
            .satisfies(e -> assertThat(e.getPhoneNumber()).as("check phoneNumber").isEqualTo(actual.getPhoneNumber()))
            .satisfies(e -> assertThat(e.getStatus()).as("check status").isEqualTo(actual.getStatus()))
            .satisfies(e -> assertThat(e.getJoinedAt()).as("check joinedAt").isEqualTo(actual.getJoinedAt()))
            .satisfies(e -> assertThat(e.getIsActive()).as("check isActive").isEqualTo(actual.getIsActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDeliveryPersonUpdatableRelationshipsEquals(DeliveryPerson expected, DeliveryPerson actual) {
        assertThat(expected)
            .as("Verify DeliveryPerson relationships")
            .satisfies(e -> assertThat(e.getAddedBy()).as("check addedBy").isEqualTo(actual.getAddedBy()))
            .satisfies(e -> assertThat(e.getZone()).as("check zone").isEqualTo(actual.getZone()));
    }
}
