package com.aps.domain;

import static com.aps.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class FishProductAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFishProductAllPropertiesEquals(FishProduct expected, FishProduct actual) {
        assertFishProductAutoGeneratedPropertiesEquals(expected, actual);
        assertFishProductAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFishProductAllUpdatablePropertiesEquals(FishProduct expected, FishProduct actual) {
        assertFishProductUpdatableFieldsEquals(expected, actual);
        assertFishProductUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFishProductAutoGeneratedPropertiesEquals(FishProduct expected, FishProduct actual) {
        assertThat(expected)
            .as("Verify FishProduct auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFishProductUpdatableFieldsEquals(FishProduct expected, FishProduct actual) {
        assertThat(expected)
            .as("Verify FishProduct relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e ->
                assertThat(e.getPricePerKg()).as("check pricePerKg").usingComparator(bigDecimalCompareTo).isEqualTo(actual.getPricePerKg())
            )
            .satisfies(e -> assertThat(e.getAvailableQuantity()).as("check availableQuantity").isEqualTo(actual.getAvailableQuantity()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()))
            .satisfies(e -> assertThat(e.getIsAvailable()).as("check isAvailable").isEqualTo(actual.getIsAvailable()))
            .satisfies(e -> assertThat(e.getCreatedAt()).as("check createdAt").isEqualTo(actual.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFishProductUpdatableRelationshipsEquals(FishProduct expected, FishProduct actual) {
        assertThat(expected)
            .as("Verify FishProduct relationships")
            .satisfies(e -> assertThat(e.getImage()).as("check image").isEqualTo(actual.getImage()));
    }
}
