package com.aps.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class OrderStatusHistoryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderStatusHistoryAllPropertiesEquals(OrderStatusHistory expected, OrderStatusHistory actual) {
        assertOrderStatusHistoryAutoGeneratedPropertiesEquals(expected, actual);
        assertOrderStatusHistoryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderStatusHistoryAllUpdatablePropertiesEquals(OrderStatusHistory expected, OrderStatusHistory actual) {
        assertOrderStatusHistoryUpdatableFieldsEquals(expected, actual);
        assertOrderStatusHistoryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderStatusHistoryAutoGeneratedPropertiesEquals(OrderStatusHistory expected, OrderStatusHistory actual) {
        assertThat(expected)
            .as("Verify OrderStatusHistory auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderStatusHistoryUpdatableFieldsEquals(OrderStatusHistory expected, OrderStatusHistory actual) {
        assertThat(expected)
            .as("Verify OrderStatusHistory relevant properties")
            .satisfies(e -> assertThat(e.getStatus()).as("check status").isEqualTo(actual.getStatus()))
            .satisfies(e -> assertThat(e.getChangeTime()).as("check changeTime").isEqualTo(actual.getChangeTime()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderStatusHistoryUpdatableRelationshipsEquals(OrderStatusHistory expected, OrderStatusHistory actual) {
        // empty method
    }
}
