package com.aps.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class RemovedOrderSummaryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRemovedOrderSummaryAllPropertiesEquals(RemovedOrderSummary expected, RemovedOrderSummary actual) {
        assertRemovedOrderSummaryAutoGeneratedPropertiesEquals(expected, actual);
        assertRemovedOrderSummaryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRemovedOrderSummaryAllUpdatablePropertiesEquals(RemovedOrderSummary expected, RemovedOrderSummary actual) {
        assertRemovedOrderSummaryUpdatableFieldsEquals(expected, actual);
        assertRemovedOrderSummaryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRemovedOrderSummaryAutoGeneratedPropertiesEquals(RemovedOrderSummary expected, RemovedOrderSummary actual) {
        assertThat(expected)
            .as("Verify RemovedOrderSummary auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRemovedOrderSummaryUpdatableFieldsEquals(RemovedOrderSummary expected, RemovedOrderSummary actual) {
        assertThat(expected)
            .as("Verify RemovedOrderSummary relevant properties")
            .satisfies(e -> assertThat(e.getUserOriginalId()).as("check userOriginalId").isEqualTo(actual.getUserOriginalId()))
            .satisfies(e -> assertThat(e.getUserName()).as("check userName").isEqualTo(actual.getUserName()))
            .satisfies(e -> assertThat(e.getUserRole()).as("check userRole").isEqualTo(actual.getUserRole()))
            .satisfies(e -> assertThat(e.getTotalOrders()).as("check totalOrders").isEqualTo(actual.getTotalOrders()))
            .satisfies(e -> assertThat(e.getTotalAmount()).as("check totalAmount").isEqualTo(actual.getTotalAmount()))
            .satisfies(e -> assertThat(e.getFirstInteractionAt()).as("check firstInteractionAt").isEqualTo(actual.getFirstInteractionAt()))
            .satisfies(e -> assertThat(e.getLastInteractionAt()).as("check lastInteractionAt").isEqualTo(actual.getLastInteractionAt()))
            .satisfies(e -> assertThat(e.getRemovedAt()).as("check removedAt").isEqualTo(actual.getRemovedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRemovedOrderSummaryUpdatableRelationshipsEquals(RemovedOrderSummary expected, RemovedOrderSummary actual) {
        // empty method
    }
}
