package com.aps.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class RemovedUserAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRemovedUserAllPropertiesEquals(RemovedUser expected, RemovedUser actual) {
        assertRemovedUserAutoGeneratedPropertiesEquals(expected, actual);
        assertRemovedUserAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRemovedUserAllUpdatablePropertiesEquals(RemovedUser expected, RemovedUser actual) {
        assertRemovedUserUpdatableFieldsEquals(expected, actual);
        assertRemovedUserUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRemovedUserAutoGeneratedPropertiesEquals(RemovedUser expected, RemovedUser actual) {
        assertThat(expected)
            .as("Verify RemovedUser auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRemovedUserUpdatableFieldsEquals(RemovedUser expected, RemovedUser actual) {
        assertThat(expected)
            .as("Verify RemovedUser relevant properties")
            .satisfies(e -> assertThat(e.getOriginalId()).as("check originalId").isEqualTo(actual.getOriginalId()))
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getRole()).as("check role").isEqualTo(actual.getRole()))
            .satisfies(e -> assertThat(e.getWhatsappNumber()).as("check whatsappNumber").isEqualTo(actual.getWhatsappNumber()))
            .satisfies(e -> assertThat(e.getPhoneNumber()).as("check phoneNumber").isEqualTo(actual.getPhoneNumber()))
            .satisfies(e -> assertThat(e.getAddress()).as("check address").isEqualTo(actual.getAddress()))
            .satisfies(e -> assertThat(e.getLocationLat()).as("check locationLat").isEqualTo(actual.getLocationLat()))
            .satisfies(e -> assertThat(e.getLocationLon()).as("check locationLon").isEqualTo(actual.getLocationLon()))
            .satisfies(e -> assertThat(e.getJoinedAt()).as("check joinedAt").isEqualTo(actual.getJoinedAt()))
            .satisfies(e -> assertThat(e.getRemovedAt()).as("check removedAt").isEqualTo(actual.getRemovedAt()))
            .satisfies(e -> assertThat(e.getReasonForRemoval()).as("check reasonForRemoval").isEqualTo(actual.getReasonForRemoval()))
            .satisfies(e -> assertThat(e.getLastSessionData()).as("check lastSessionData").isEqualTo(actual.getLastSessionData()))
            .satisfies(e -> assertThat(e.getStatus()).as("check status").isEqualTo(actual.getStatus()))
            .satisfies(e -> assertThat(e.getOrderHistoryId()).as("check orderHistoryId").isEqualTo(actual.getOrderHistoryId()))
            .satisfies(e ->
                assertThat(e.getDistanceFromBusinessKm()).as("check distanceFromBusinessKm").isEqualTo(actual.getDistanceFromBusinessKm())
            )
            .satisfies(e -> assertThat(e.getIsPincodeValid()).as("check isPincodeValid").isEqualTo(actual.getIsPincodeValid()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRemovedUserUpdatableRelationshipsEquals(RemovedUser expected, RemovedUser actual) {
        // empty method
    }
}
