package com.aps.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ReturnStatusHistoryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReturnStatusHistoryAllPropertiesEquals(ReturnStatusHistory expected, ReturnStatusHistory actual) {
        assertReturnStatusHistoryAutoGeneratedPropertiesEquals(expected, actual);
        assertReturnStatusHistoryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReturnStatusHistoryAllUpdatablePropertiesEquals(ReturnStatusHistory expected, ReturnStatusHistory actual) {
        assertReturnStatusHistoryUpdatableFieldsEquals(expected, actual);
        assertReturnStatusHistoryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReturnStatusHistoryAutoGeneratedPropertiesEquals(ReturnStatusHistory expected, ReturnStatusHistory actual) {
        assertThat(expected)
            .as("Verify ReturnStatusHistory auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReturnStatusHistoryUpdatableFieldsEquals(ReturnStatusHistory expected, ReturnStatusHistory actual) {
        assertThat(expected)
            .as("Verify ReturnStatusHistory relevant properties")
            .satisfies(e -> assertThat(e.getStatus()).as("check status").isEqualTo(actual.getStatus()))
            .satisfies(e -> assertThat(e.getChangeTime()).as("check changeTime").isEqualTo(actual.getChangeTime()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReturnStatusHistoryUpdatableRelationshipsEquals(ReturnStatusHistory expected, ReturnStatusHistory actual) {
        assertThat(expected)
            .as("Verify ReturnStatusHistory relationships")
            .satisfies(e -> assertThat(e.getReturnedOrder()).as("check returnedOrder").isEqualTo(actual.getReturnedOrder()));
    }
}
