package com.aps.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ReturnedOrderItemAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReturnedOrderItemAllPropertiesEquals(ReturnedOrderItem expected, ReturnedOrderItem actual) {
        assertReturnedOrderItemAutoGeneratedPropertiesEquals(expected, actual);
        assertReturnedOrderItemAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReturnedOrderItemAllUpdatablePropertiesEquals(ReturnedOrderItem expected, ReturnedOrderItem actual) {
        assertReturnedOrderItemUpdatableFieldsEquals(expected, actual);
        assertReturnedOrderItemUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReturnedOrderItemAutoGeneratedPropertiesEquals(ReturnedOrderItem expected, ReturnedOrderItem actual) {
        assertThat(expected)
            .as("Verify ReturnedOrderItem auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReturnedOrderItemUpdatableFieldsEquals(ReturnedOrderItem expected, ReturnedOrderItem actual) {
        assertThat(expected)
            .as("Verify ReturnedOrderItem relevant properties")
            .satisfies(e -> assertThat(e.getQuantity()).as("check quantity").isEqualTo(actual.getQuantity()))
            .satisfies(e -> assertThat(e.getProductComment()).as("check productComment").isEqualTo(actual.getProductComment()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReturnedOrderItemUpdatableRelationshipsEquals(ReturnedOrderItem expected, ReturnedOrderItem actual) {
        assertThat(expected)
            .as("Verify ReturnedOrderItem relationships")
            .satisfies(e -> assertThat(e.getProduct()).as("check product").isEqualTo(actual.getProduct()))
            .satisfies(e -> assertThat(e.getReturnedOrder()).as("check returnedOrder").isEqualTo(actual.getReturnedOrder()));
    }
}
