package com.aps.domain;

import static com.aps.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class ReturnedOrderAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReturnedOrderAllPropertiesEquals(ReturnedOrder expected, ReturnedOrder actual) {
        assertReturnedOrderAutoGeneratedPropertiesEquals(expected, actual);
        assertReturnedOrderAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReturnedOrderAllUpdatablePropertiesEquals(ReturnedOrder expected, ReturnedOrder actual) {
        assertReturnedOrderUpdatableFieldsEquals(expected, actual);
        assertReturnedOrderUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReturnedOrderAutoGeneratedPropertiesEquals(ReturnedOrder expected, ReturnedOrder actual) {
        assertThat(expected)
            .as("Verify ReturnedOrder auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReturnedOrderUpdatableFieldsEquals(ReturnedOrder expected, ReturnedOrder actual) {
        assertThat(expected)
            .as("Verify ReturnedOrder relevant properties")
            .satisfies(e -> assertThat(e.getReturnDate()).as("check returnDate").isEqualTo(actual.getReturnDate()))
            .satisfies(e ->
                assertThat(e.getPaymentReceivedMode()).as("check paymentReceivedMode").isEqualTo(actual.getPaymentReceivedMode())
            )
            .satisfies(e ->
                assertThat(e.getPaymentReturnedMode()).as("check paymentReturnedMode").isEqualTo(actual.getPaymentReturnedMode())
            )
            .satisfies(e -> assertThat(e.getProductClaimStatus()).as("check productClaimStatus").isEqualTo(actual.getProductClaimStatus()))
            .satisfies(e ->
                assertThat(e.getRefundAmount())
                    .as("check refundAmount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(actual.getRefundAmount())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReturnedOrderUpdatableRelationshipsEquals(ReturnedOrder expected, ReturnedOrder actual) {
        assertThat(expected)
            .as("Verify ReturnedOrder relationships")
            .satisfies(e -> assertThat(e.getOrder()).as("check order").isEqualTo(actual.getOrder()))
            .satisfies(e -> assertThat(e.getCustomer()).as("check customer").isEqualTo(actual.getCustomer()));
    }
}
