package com.aps.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TeamMemberAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTeamMemberAllPropertiesEquals(TeamMember expected, TeamMember actual) {
        assertTeamMemberAutoGeneratedPropertiesEquals(expected, actual);
        assertTeamMemberAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTeamMemberAllUpdatablePropertiesEquals(TeamMember expected, TeamMember actual) {
        assertTeamMemberUpdatableFieldsEquals(expected, actual);
        assertTeamMemberUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTeamMemberAutoGeneratedPropertiesEquals(TeamMember expected, TeamMember actual) {
        assertThat(expected)
            .as("Verify TeamMember auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTeamMemberUpdatableFieldsEquals(TeamMember expected, TeamMember actual) {
        assertThat(expected)
            .as("Verify TeamMember relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getWaPhoneNumber()).as("check waPhoneNumber").isEqualTo(actual.getWaPhoneNumber()))
            .satisfies(e -> assertThat(e.getPhoneNumber()).as("check phoneNumber").isEqualTo(actual.getPhoneNumber()))
            .satisfies(e -> assertThat(e.getRole()).as("check role").isEqualTo(actual.getRole()))
            .satisfies(e -> assertThat(e.getIsActive()).as("check isActive").isEqualTo(actual.getIsActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTeamMemberUpdatableRelationshipsEquals(TeamMember expected, TeamMember actual) {
        // empty method
    }
}
