package com.aps.domain.enumeration;

/**
 * The AdminFlowStage enumeration.
 */
public enum AdminFlowStage {
    IDLE,
    // Customer Flow
    CUSTOMER_MENU,
    AWAITING_CUST_NAME,
    AWAITING_CUST_PHONE,
    AWAITING_CUST_WAPHONE,
    AWAITING_CUST_LOCATION,
    CONFIRMING_CUST_ADD,
    AWAITING_DELETE_CUST_ID, // Added for Phase B

    // Product Flow
    PRODUCT_MENU,
    AWAITING_PRODUCT_NAME,
    AWAITING_PRODUCT_PRICE,
    AWAITING_PRODUCT_DESCRIPTION,
    AWAITING_PRODUCT_AVAILABILITY,
    AWAITING_PRODUCT_IMAGES, // Added

    // Delivery Flow
    DELIVERY_MENU,
    AWAITING_DELIVERY_NAME,
    AWAITING_DELIVERY_PHONE,
    AWAITING_DELIVERY_WAPHONE,
    AWAITING_DELIVERY_STATUS,
    CONFIRMING_DELIVERY_ADD,
    AWAITING_DELETE_DELIVERY_ID, // Added for Phase B

    // Executive Flow
    EXECUTIVE_MENU,
    AWAITING_EXEC_NAME,
    AWAITING_EXEC_PHONE,
    AWAITING_EXEC_WAPHONE,
    AWAITING_EXEC_STATUS,
    CONFIRMING_EXEC_ADD,

    // Assistant Flow
    ASSISTANT_MENU,
    AWAITING_ASSISTANT_NAME,
    AWAITING_ASSISTANT_PHONE,
    AWAITING_ASSISTANT_WAPHONE,
    AWAITING_ASSISTANT_STATUS,
    PROCESSING,
    CONFIRMING_ASSISTANT_ADD,

    // Accounts Flow
    ACCOUNTS_MENU,
    AWAITING_ACC_NAME,
    AWAITING_ACC_PHONE,
    AWAITING_ACC_WAPHONE,
    AWAITING_ACC_STATUS,
    CONFIRMING_ACC_ADD,
}
