export enum OrderStatus {
  ORDER_NOT_TAKEN = 'ORDER_NOT_TAKEN',
  DELIVERY_ONWAY = 'DELIVERY_ONWAY',
  ORDER_DELIVERED_SUCESSFULLY = 'ORDER_DELIVERED_SUCESSFULLY',
  ORDER_FAILED = 'ORDER_FAILED',
}
