export enum UserRole {
  CUSTOMER = 'CUSTOMER',

  EXECUTIVE = 'EXECUTIVE',

  DELIVERY_PERSON = 'DELIVERY_PERSON',

  ASSISTANT_ADMIN = 'ASSISTANT_ADMIN',

  ADMIN = 'ADMIN',

  DEVELOPER = 'DEVELOPER',
}
